### PR TITLE
INSTALL.md - Describe install of tomatoes

### PR DESCRIPTION
**Pull request by Darksider3**
The INSTALL.md describes how to install an own instance of tomatoes.
See #257

### CODE REVIEW

**Comment by Darksider3** [comment]
Just wondering - What's the status here?

**Comment by potomak** [comment]
@Darksider3 I'm sorry, but I'm against adding this file in the repo.

For instance I don't use RVM and I'm not a Linux user. It would be hard to include here information on how to install Tomatoes on all the different combinations of OS/package managers/etc.

The most generic way to install this project would be to use some kind of VPS or VPC, so I'd rather work on https://github.com/tomatoes-app/tomatoes/issues/128. This would also make it easier to give support to people who fail to install the app for whatever reason.

I think it would be just better for you to create a post somewhere where you suggest this as *a way* to setup the project.

**Comment by Darksider3** [comment]
Atleast, the most generic ways in my opinion is RVM(Support Windows, Mac, Linux)/RBenv(Mac, Linux).
The thing with an installation document is: I don't have to actually read trough all your dependency-files and even without knowledge of programming itself, i could be able to install it.
Describing ALL POSSIBLE WAYS wasn't the intention too.
The purpose was to **lower** the hurdle for folks that want to contribute *or* to set it up themself, to use it e.g. at a local work page, or similar. Heck, or even to programm against the API it would be usefull.
Therefore i wanted to give some **minimal steps** to install Tomatoes. That's all what many projects out there give you. And that is most of the time enough.

Listing dependencies, easiest installation process, done. 
With dependencies it's even for non-programmers possible to install them on their preferred way, or use google to get all packages together. But listing exactly nothing for the sake of "can't cover everything in this world" doesn't lower it.

For example, say, someone wants his language as an option: He can't test it. Just only because he doesn't know how to install.
If there would be an Plugin interface for different languages, how someone could test his plugins without the knowledge to setup initially?
Programming locally against the API is easier with a local counterpart of the application. 

But i think, you got what i wanted to say. ^^'

**Comment by potomak** [comment]
@Darksider3 I agree with you. The reason why I didn't accept this PR is that I don't think this document should be part of the repo.

I think it would be a great introductory article on how to setup a Tomatoes app locally for a personal blog. I'd be happy to share it through Tomatoes' twitter account if you publish such post.

**Pull request closed without merging**
